---
- name: "copy iptables fragment rules for {{ name }}"
  copy:
    content: |
      # fragment for {{ comment }}
      {{ content }}
    dest: "{{ iptables_fragments_folder }}/{{ order }}-{{ name }}"

- name: "assemble iptables fragment"
  assemble:
    src: "{{ iptables_fragments_folder }}"
    dest: "{{ iptables_sysconfig_path }}"
    validate: "{{ iptables_restore_cmd }} --test %s"
  when:
    - reload|default(true)|bool
  notify:
    - reload iptables service
