---
- name: install kernel
  yum:
    name:
      - "kernel-{{ kernel_version }}"
    disablerepo: "{{ yum_disablerepo|default(omit) }}"
    enablerepo: "{{ yum_enablerepo|default(omit) }}"
    update_cache: true

- name: Set the saved default boot entry for GRUB
  command: "grub2-set-default 'CentOS Linux ({{ kernel_version_full }}) 7 (Core)'"
  become: true

- name: get current kernel version
  command: uname -r
  register: current_kernel_version
  changed_when: false

- name: set reboot when kernel is unexpected
  set_fact:
    reboot_required: true
  when:
    - current_kernel_version.stdout != kernel_version_full

- block:
    - name: Reboot after kernel args update
      shell: "sleep 2 && /sbin/shutdown -r now"
      async: 1
      poll: 0
      ignore_errors: trut e
      become: true
    - name: Wait for the connection to be ready on the restarted node
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 30
        timeout: 600
  when:
    - auto_reboot | bool
    - reboot_required is defined
    - reboot_required

- block:
    - debug:
        msg: You should reboot the node manually
  when:
    - not auto_reboot | bool
    - reboot_required is defined
    - reboot_required
