---
network_config:
  # Config Management Network Bond
  - type: linux_bridge
    name: br-bond1
    use_dhcp: false
    mtu: {{ mtu | int }}
    members:
      - type: linux_bond
        name: bond1
        mtu: {{ mtu | int }}
        bonding_options: mode=1 miimon=100
        members:
          - type: interface
            name: nic1
            mtu: {{ mtu | int }}
            primary: true
          - type: interface
            name: nic2
            mtu: {{ mtu | int }}
    dns_servers: []
    domain: []

  # Config ControlPlane Network VlanID
  - type: vlan
    vlan_id: 121
    device: br-bond1
    mtu: {{ mtu | int }}
    addresses:
      - ip_netmask: "{{ control_subnet | ipmath(node_id) }}/{{ control_subnet | ipaddr('prefix') }}"
    routes:
      - default: true
        next_hop: "{{ control_gateway }}"

  # Config InternalApi Network VlanID
  - type: vlan
    vlan_id: 122
    device: br-bond1
    mtu: {{ mtu | int }}
    addresses:
      - ip_netmask: "{{ internal_subnet | ipmath(node_id) }}/{{ internal_subnet | ipaddr('prefix') }}"

  # Config External Network VlanID
  - type: vlan
    vlan_id: 123
    device: br-bond1
    mtu: {{ mtu | int }}
    addresses:
      - ip_netmask: "{{ public_subnet | ipmath(node_id) }}/{{ public_subnet | ipaddr('prefix') }}"

  # Config Storage Network Bond
  - type: linux_bridge
    name: br-bond2
    use_dhcp: false
    mtu: {{ mtu | int }}
    members:
      - type: linux_bond
        name: bond2
        mtu: {{ mtu | int }}
        bonding_options: mode=1 miimon=100
        members:
          - type: interface
            name: nic3
            mtu: {{ mtu | int }}
            primary: true
          - type: interface
            name: nic4
            mtu: {{ mtu | int }}
    dns_servers: []
    domain: []

  # Config StorageMgmt Network VlanID
  - type: vlan
    vlan_id: 124
    device: br-bond2
    mtu: {{ mtu | int }}
    addresses:
      - ip_netmask: "{{ storagemgmt_subnet | ipmath(node_id) }}/{{ storagemgmt_subnet | ipaddr('prefix') }}"

  # Config Storage Network VlanID
  - type: vlan
    vlan_id: 125
    device: br-bond2
    mtu: {{ mtu | int }}
    addresses:
      - ip_netmask: "{{ storage_subnet | ipmath(node_id) }}/{{ storage_subnet | ipaddr('prefix') }}"

  # Config Tenant Network Bond
  - type: ovs_user_bridge
    name: br-ex
    members:
      - type: ovs_dpdk_bond
        name: dpdkbond0
        mtu: {{ mtu | int }}
        rx_queue: 4
        members:
          - type: ovs_dpdk_port
            name: dpdk0
            driver: "{{ dpdk_driver }}"
            members:
              - type: interface
                name: nic5
          - type: ovs_dpdk_port
            name: dpdk1
            driver: "{{ dpdk_driver }}"
            members:
              - type: interface
                name: nic6
