---
packages:
  infra:
    - bridge-utils
    - patch
    - tuned
    - tuned-profiles-cpu-partitioning
  opstool:
    - python2-pip
    - bash-completion
    - bind-utils
    - curl
    - dstat
    - e2fsprogs
    - ethtool
    - findutils
    - fping
    - git
    - htop
    - httpd
    - iftop
    - iotop
    - iperf3
    - iproute
    - jq
    - lsof
    - net-tools
    - nmap-ncat
    - numactl
    - parallel
    - patch
    - pciutils
    - perf
    - procps-ng
    - psmisc
    - strace
    - sysstat
    - tcpdump
    - telnet
    - tmux
    - traceroute
    - unzip
    - vim-enhanced
    - wget
  client:
    - mariadb
    - libvirt-client
    - qemu-img-ev
  openstack:
    - python2-barbicanclient
    - python2-heatclient
    - python2-ironicclient
    - python2-netaddr
    - python2-openstackclient
    - python2-openstacksdk
