---
hugepages: 0
hugepagesz: 1G

tuned_profile: ict-virtual-host

ip_version: "4"

auto_reboot: true

sriov_vfs: 0

###########
# address #
###########
# control & provision network
control_subnet:
control_vlanid:
control_gateway:
control_mtu: 1500
control_address: "{{ control_subnet|ipmath(node_id) }}"
control_prefix: "{{ control_subnet|ipaddr('prefix') }}"

# openstack public network
public_subnet:
public_vlanid:
public_gateway:
public_mtu: 1500
public_address: "{{ public_subnet|ipmath(node_id) }}"
public_prefix: "{{ public_subnet|ipaddr('prefix') }}"

# openstack internal network
internal_subnet:
internal_vlanid:
internal_gateway:
internal_mtu: 1500
internal_address: "{{ internal_subnet|ipmath(node_id) }}"
internal_prefix: "{{ internal_subnet|ipaddr('prefix') }}"

# openstack admin network
# TODO: this is not supported by kolla
admin_subnet:
admin_vlanid:
admin_gateway:
admin_mtu: 1500
admin_address: "{{ admin_subnet|ipmath(node_id) }}"
admin_prefix: "{{ admin_subnet|ipaddr('prefix') }}"

# ceph public network & storage data network
storage_subnet:
storage_vlanid:
storage_gateway:
storage_mtu: 1500
storage_address: "{{ storage_subnet|ipmath(node_id) }}"
storage_prefix: "{{ storage_subnet|ipaddr('prefix') }}"

# ceph cluster network & storage management network
storagemgmt_subnet:
storagemgmt_vlanid:
storagemgmt_gateway:
storagemgmt_mtu: 1500
storagemgmt_address: "{{ storagemgmt_subnet|ipmath(node_id) }}"
storagemgmt_prefix: "{{ storagemgmt_subnet|ipaddr('prefix') }}"

# tenant network, used by virtual machine
tenant_subnet:
tenant_vlanid:
tenant_gateway:
tenant_mtu: 1500
tenant_address: "{{ tenant_subnet|ipmath(node_id) }}"
tenant_prefix: "{{ tenant_subnet|ipaddr('prefix') }}"

##########
# Domain #
##########
domain_prefix: overcloud
domain_suffix: vim1.local

internal_domain_infix: internal
public_domain_infix: public
control_domain_infix: control
storage_domain_infix: storage
storagemgmt_domain_infix: storagemgmt

default_domain: "{{ ansible_hostname }}"
default_domain_fqdn: "{{ default_domain }}.{{ domain_suffix }}"

public_domain: "{{ ansible_hostname }}.{{ public_domain_infix }}"
public_domain_fqdn: "{{ public_domain }}.{{ domain_suffix }}"

control_domain: "{{ ansible_hostname }}.{{ control_domain_infix }}"
control_domain_fqdn: "{{ control_domain }}.{{ domain_suffix }}"

internal_domain: "{{ ansible_hostname }}.{{ internal_domain_infix }}"
internal_domain_fqdn: "{{ internal_domain }}.{{ domain_suffix }}"

storage_domain: "{{ ansible_hostname }}.{{ storage_domain_infix }}"
storage_domain_fqdn: "{{ storage_domain }}.{{ domain_suffix }}"

storagemgmt_domain: "{{ ansible_hostname }}.{{ storagemgmt_domain_infix }}"
storagemgmt_domain_fqdn: "{{ storagemgmt_domain }}.{{ domain_suffix }}"

###################
# node infomation #
###################
api_interface: "{{ network_interface }}"
