---
###########
# network #
###########
interface_mapping_yaml: ""
os_net_config_yaml: ""
control_subnet: ""
public_subnet: ""
internal_subnet: ""
storage_subnet: ""
storagemgmt_subnet: ""
control_gateway: ""
mtu: 1500
enable_network_container: false
enable_network_check: true

########
# DPDK #
########

dpdk_driver: "{{ 'vfio-pci' if ansible_virtualization_role =='host' else 'uio_pci_generic' }}"

##########
# docker #
##########
docker_registry: ""
os_net_config_image: "os-net-config/os-net-config"
os_net_config_image_full: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ os_net_config_image }}"
