---
- name: init /etc/kolla/config folder
  file:
    path: /etc/kolla/config
    state: directory

- name: check whether the custom conf file exist
  stat:
    path: "/etc/kolla/config/{{ item }}"
  register: check_custom_conf
  with_items: "{{ custom_config_files }}"

- name: ensure the parent folder for custom conf
  file:
    path: "/etc/kolla/config/{{ item|dirname }}"
    state: directory
    recurse: true
  when:
    - item.find('/') != -1
  with_items: "{{ custom_config_files }}"

- name: copy service conf files
  template:
    src: "{{ item.item }}"
    dest: "/etc/kolla/config/{{ item.item }}"
  when:
    - custom_config_overwrite | bool or not item.stat.exists
  with_items: "{{ check_custom_conf.results }}"
