---
- name: ensure /etc/ansible/hosts folder
  import_role:
    name: ansible
    tasks_from: ensure_hosts.yml

- name: check prometheus groups file
  stat:
    path: /etc/ansible/hosts/50-prom-groups
  register: check_prom_groups

- name: copy /etc/ansible/hosts/50-prom-groups file
  copy:
    src: groups
    dest: /etc/ansible/hosts/50-prom-groups
  when:
    - not check_prom_groups.stat.exists
